- src/creds/definitions.js
I forgot to add the document image
> add document images to document credential

- __test__/creds/VerifiableCredential.test.js
- __test__/uca/UserCollectableAttributes.test.js
- src/creds/VerifiableCredential.js
- src/isClaimRelated.js
- src/uca/UserCollectableAttribute.js
This helper function is useful to find types using their internal properties
> Adding getAllProperties to UCA and VCs 

- __test__/index.test.js
- package-lock.json
- package.json
Adding an pre-commit hook with npm run lint
> Adding husky precommit hook and npm run lint to it

- .circleci/config.yml
Release process routine for publishing credential-commons into npm.
This workflow is following the official documented process from Circle CI:
https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/
> Release process

- .circleci/config.yml
- package-lock.json
- package.json
- New package name that refers to identiy.com organization.
- Using contexts in circleci build.
> Improving Release process

- package-lock.json
Fixed vulnerabilities mentioned by Github.
I've just run `npm audit fix` and everything seems to be fine now!
> Fixing npm dependencies vulnerabilities

- .circleci/config.yml
-Only start release process when a tag following the pattern vX.X.X-rcX is created.
-- Circleci will build, increment package.json version, create a tag in the pattern: vX.X.X
-- Circleci will see this new tag start the publish workflow: build and publish it on npm
This process was discussed with Daniel K and Fernando.
> CCS-553 automatic versioning after a tag is created

- README.md
Adding version and build badges on README.md
> Adding version and build badges

- __test__/creds/VerifiableCredential.test.js
- package-lock.json
Added a test for filtering credentials and receiving no claim
> Testing for empty filtering

- __test__/claim/Claim.test.js
- package-lock.json
Just adding a test case to show how to transform a UCA into a Claim.
> Transforming UCA to Claim test case

- __test__/creds/VerifiableCredentialSchema.test.js
- src/claim/Claim.js
- src/claim/definitions.js
- src/creds/definitions.js
- src/schemas/generator/SchemaGenerator.js
- Created IDaaS credential
- Fixed generation of string random values that must be compliant with a regex pattern
> Creating IDaaS credential

- .circleci/config.yml
Improve release process - Update hub version and make sure it does not fail if '.config' folder is already created
> Improve release process - Update hub version

- package-lock.json
- src/creds/VerifiableCredential.js
Two parameters were being passed on the anchor method and they are now on the options array
> Removing parameter passing as they are now on options array

- src/services/DummyAnchorServiceImpl.js
Changed the dummy implementation to match others
> Updating dummy implementation to match other anchor plugins

- scripts/generateSchemas.js
- scripts/publishSchemas.js
- src/schemas/generator/SchemaGenerator.js
- Supporting UCA's in the schema generation
> Supporting UCA's in the schema generation

- __test__/creds/VerifiableCredential.test.js
- package-lock.json
- src/creds/VerifiableCredential.js
Changed credential matches logic to new identifiers
> Fixing credential matching

- __test__/claim/Claim.test.js
- __test__/creds/VerifiableCredential.test.js
- package-lock.json
- package.json
- src/claim/Claim.js
- src/creds/VerifiableCredential.js
- Refer to 'credentialItem' instead of 'credentialIdentifier'
> CCS-821 - Refer to 'credentialItem' instead of 'credentialIdentifier'

- src/creds/definitions.js
- Fixing idvaaService credential name
> CCS-842 - Fixing idvaaService credential name

- __test__/isValidGlobalIdentifier.test.js
- package-lock.json
- src/claim/definitions.js
Mobile screens doesn't have the unit field as required, being optional
> Removing unit as required

- package.json
- #71 Common IDV errors exposed
- #72 Address:unit is not required
> Releasing 1.0.0-rc.1

- package.json
> Releasing v1.0.0-rc.5

- package.json
> Feature/cvc 1236  add external id header

- package-lock.json
- package.json
- src/claim/Claim.js
- src/errors/definitions.js
- Adding new error key
- Bugfix - How the attestable values are initialized
- Versioning to 1.0.0-rc.8
> CCS-871 - call verify method on build dsr response

- package.json
- src/constants/headers.js
Added Identity header definition for self-signed JWT tokens
> Added Identity Header

- package-lock.json
- package.json
Updated UCA module version to 1.0.1
> updated uca version to 1.0.1

- __test__/creds/VerifiableCredential.test.js
- package-lock.json
This adds a new test for the new document credential
> adding a new test for 'credendial-cvc:IdDocument-v1'

- package-lock.json
- package.json
Update uca to `v1.0.3`.
Update credential-commons version to `v1.0.5`.
> Update UCA library version

- package-lock.json
- package.json
Update `@identity/uca` version to `1.0.3`.
Update Credential commons to `v1.0.8`.
> Update uca version

- package-lock.json
- package.json
- src/claim/Claim.js
Fix Claim initialization according to the changes on `@identity.com/uca`: make definitions immutable.
Update `credential-commons` version to `1.0.12`.
> Fix Claim initialization

- package-lock.json
- package.json
Update `@identity.com/uca` to `1.0.7`.
> Update dependency version

- package-lock.json
- package.json
Update `@identity.com/uca` version to `1.0.8`.
Update version to `1.0.14`.
> Update UCA version to 1.0.8

- __test__/claim/Claim.test.js
- package-lock.json
- package.json
Add a test for claim transformation when UCA is an alias to another UCA (the UCA type is another UCA identifier).
> Test claim conversion for alias UCAs

- package-lock.json
- package.json
- src/index.js
Expose Claims and Credentials definitions.
Bump version to `1.0.27`.
> Expose definitions

- package-lock.json
- package.json
- src/constants/headers.js
Define new header in constants:
```
FLOW_ID_HEADER: 'X-Civic-FlowId'
```
> Define Flow ID Header in Constants

- __test__/creds/VerifiableCredential.test.js
- package-lock.json
- package.json
- src/creds/definitions.js
Defines the new 'credential-alt:Identity-v1'
> ID-1316 new credential definition

- package-lock.json
- src/errors/definitions.js
- Adding new network retryable error
> [CIV-249] Adding retryable network error

- package-lock.json
- package.json
- Updating the version on package.json to release
> Updating the version to 1.0.33

- scripts/generateSchemas.js
Fix for error during Circle build
> removed unused uuid/v4 declaration

- .circleci/config.yml
Use Node 12 for Circle schema jobs
> updated circle image to node 12

- package.json
bump package release version to allow automated Circle release
> update release version

- __test__/claim/Claim.test.js
- __test__/creds/VerifiableCredential.test.js
- src/claim/definitions.js
Added new claim attributes:
- test and vaccination ids
- added 'organisation' to test
> added test and vaccination ids

- audit-ci.json
- package-lock.json
- package.json
> bumb UCA version to 1.0.26

- package-lock.json
- package.json
> CIV-3183 - Upgrade UCA lib

- __test__/creds/VerifiableCredential.test.js
- __test__/creds/fixtures/filteredIdDocument-v2.json
- package-lock.json
- package.json
- src/creds/VerifiableCredential.js
There is situation where we need to hydrate de credential from a json string but we only have a partial implementaion.
This add a flag the the fromJSON method to skip the required claims validation if we are trying to use a partial presentation.
> Handling presentations from json
