identity-com/credential-commons

__test__/uca/UserCollectableAttributes.test.js, src/uca/definitions.js
By definition, an "Email Address" is the broader definition, and is is composed by `username @ domainname` (ref: https://techterms.com/definition/email_address). Calling the username part as "address" may create a confusion on future. This PR change `Email:address` to `Email:username`
=> better email naming definition

__test__/uca/UserCollectableAttributes.test.js, src/uca/definitions.js
This is another version for https://github.com/identity-com/credential-commons-js/pull/6, `local part` is used by some definition similar to `username` part of the email address (ref: https://en.wikipedia.org/wiki/Email_address). This PR changes `address` to `username` and domain `local_part` do domain `name`.
=> better email naming definition 2

.eslintignore, .eslintrc, __integrations__/schemas/PublicSchemasValidation.test.js, __test__/creds/VerifiableCredential.test.js, __test__/creds/VerifiableCredentialSchema.test.js, __test__/isClaimRelated.test.js, __test__/services/configBranch.test.js, __test__/uca/UserCollectableAttributes.test.js, __test__/uca/UserCollectableAttributesSchemas.test.js, __test__/uca/UserCollectableAttributesSchemasMocks.test.js, package-lock.json, package.json, src/creds/VerifiableCredential.js, src/isClaimRelated.js, src/schemas/generator/SchemaGenerator.js, src/services/DummyAnchorServiceImpl.js, src/services/__mocks__/httpService.js, src/services/anchorService.js, src/uca/UserCollectableAttribute.js
Fix lint command to check folders recursively.
Proposed changes:
- Make lint command generic: `eslint .`, instead of specifying each folder to be checked. A `.eslintignore` file was added for files/folders to be ignored. 
- Add `lint:fix` command (fix simple lint errors)
- Change `max-len` rule to warn when line is longer than 120 characters (it was 200).
- Fix lint errors
=> Improve lint checks

src/creds/VerifiableCredential.js, src/index.js, src/services/index.js
Anchor service can be overridden by a plugin. The way to do it is the following:
```
//plugin project
const MyCustomAnchorServiceImpl  = require('./MyCustomAnchorServiceImpl');
function init(services){
services.resetProviders('AnchorService');
services.service('AnchorService', MyCustomAnchorServiceImpl, 'Config', 'Http');
}
```
```
//project that depends credential-commons
const credentialCommons = require('@identity.com/credential-commons');
require('my-custom-anchor-credential-commons-plugin')(credentialCommons);
```
=> Enabling anchor service plugins

.circleci/config.yml
The release process is triggered by the creation of a release tag that following the pattern 'vX.X.X-release.X. Ex.: 'v1.0.0-release.1'.
After the process is done this tag is not needed anymore because another one will be created by CI.
=> Deleting release tag after the process is done

package-lock.json, package.json, src/errors/idvErrors.js, src/errors/index.js, src/index.js
The credential-wallet (CW) needs a way to get more detailed errors back from the IDV-toolkit. The idvErrors module contains the definitions for the error details that will be sent from the IDV-toolkit when an error is thrown.
The CW will parse a HTTP error response.body returned by the IDV-toolkit by instantiating an IDVError object like:
`const idvError = new IDVError(response.body);`
the idvError.errorCode and idvError.errorContext can then be used to create custom messages/responses to be passed to the frontend/user
=> Feature/cvc 1163  add shared idv error classes to the credential commons library

package-lock.json, src/errors/definitions.js, src/errors/idvErrors.js, src/errors/index.js
- Changes the `idvErrorCodes` to a generic `ErrorCodes`. The old ones is still valid - retrofit - but should be deprecated on the future;
- Moves all other CW error codes to CredentialCommons ErrorCodes;
=> CCS-855 moves CW errors to the shared library

__test__/creds/VerifiableCredential.test.js, src/creds/VerifiableCredential.js
- fixed `isMatchCredentialMeta`, now matching by any credential metadata other them `credential`
=> bugfix/CCS-884 isMatchCredentialMeta is not properly matching by issuer

src/constants/headers.js, src/constants/index.js, src/index.js
As agreed at the ExternalId meeting on 04/03/2019, an 'external id' header is required to be added to requests/responses from the Credential Wallet to the IDV-Toolkit. This PR adds the header definition so it can be referenced as a common definition by the CW and IDV-toolkit.
The choice of 'X-External-ID' is to reflect the generic nature of the ID, and appropriate HTTP header naming conventions.
=> added initial HeaderType externalId definition

.circleci/config.yml, README.md
Update CI configuration to publish schemas as follows:
- publish schemas to dev on every commit in the master
- publish schemas to prod on every new release
=> CCS-800 - Automate schemas publishing

__test__/isValidGlobalIdentifier.test.js, package.json, src/creds/definitions.js
Fix a typo in the `credential-cvc:IdDocument-v1` definition and update version to `1.0.3`.
=> Fix idDocument definition

__test__/creds/VerifiableCredential.test.js, src/creds/VerifiableCredential.js
Add support for constrains like:
{ path: 'identity.dateOfBirth', is: { $lt: 1554377905342 } },
{ path: 'identity.dateOfBirth', is: { $gte: '-18y' } },
=> ID-111 support constraints for parent path

README.md, __test__/creds/VerifiableCredential.test.js, package-lock.json, package.json, src/creds/VerifiableCredential.js
Add support to include `evidence` in a verifiable credential in order to provide the verifier with additional supporting information.
For more details, please refer to the [Evidence session in Verifiable Credential Data Model 1.0](https://www.w3.org/TR/verifiable-claims-data-model/#evidence).
The evidence is an optional parameter on VC construction:
``` 
const name = new Claim.IdentityName({ first: 'Joao', middle: 'Barbosa', last: 'Santos' });
const dob = new Claim.IdentityDateOfBirth({ day: 20, month: 3, year: 1978 });
const evidence = {
id: 'https://idv.civic.com/evidence/f2aeec97-fc0d-42bf-8ca7-0548192dxyzab',
type: ['DocumentVerification'],
verifier: 'did:ethr:xxx',
evidenceDocument: 'Brazilian Passport',
subjectPresence: 'Digital',
documentPresence: 'Digital',
};
const cred = new …
```
=> ID-105 - Add support to set evidence in a verifiable credential

__test__/creds/VerifiableCredential.test.js, src/creds/VerifiableCredential.js
the original code `const claimValue = _.get(claims, leave.claimPath);`
returns an object like `{day: 1, month: 1, year: 1}` but the expectation was to an object like `{dateOfBirth:  {day: 1, month: 1, year: 1}}`
Because of that on the test line
`if (expectedClaimValue && _.get(ucaValueValue[k], 'value') != expectedClaimValue)`
`expectedClaimValue` was always undefined preventing the check at all, never pushing it to the `invalidValues`
=> This fix the credential values comparison inside the `verify` function.

__test__/creds/VerifiableCredential.test.js, __test__/creds/fixtures/IdDocumentWithoutNonRequiredClaims.json, __test__/creds/fixtures/IdDocumentWithoutRequiredClaims.json, src/creds/VerifiableCredential.js, src/creds/definitions.js
Credential definition now supports a `required` attribute with the list of mandatory claims. The required claims are checked on Verifiable Credential construction (when using the regular constructor or building from JSON).
Required claims were defined for the `idDocument` credential:
```
{
identifier: 'credential-cvc:IdDocument-v1',
version: '1',
depends: [
'claim-cvc:Document.type-v1',
'claim-cvc:Document.number-v1',
'claim-cvc:Document.name-v1',
'claim-cvc:Document.gender-v1',
'claim-cvc:Document.issueCountry-v1',
'claim-cvc:Document.placeOfBirth-v1',
'claim-cvc:Document.dateOfBirth-v1',
'claim-cvc:Document.dateOfExpiry-v1',
'claim-cvc:Document.nationality-v1',
],
required: [
'claim-cvc:Document.type-v1',
'claim-cvc:Document.name-v1',
'claim-cvc:Document.dateOfBirth-v1', …
```
=> Add support to required claims in the credentials definition

__test__/creds/VerifiableCredential.test.js, __test__/creds/fixtures/IdDocumentWithoutNonRequiredClaims.json, package-lock.json, package.json, src/claim/definitions.js, src/creds/definitions.js, src/schemas/generator/SchemaGenerator.js
Adds: `claim-cvc:Document.evidences-v1` to `credential-cvc:IdDocument-v1`
Fix:  `claim-cvc:Document.type-v1` now it validates usuing the corret UCA enum
Update: SchemaGenerator to support enuns when creating random values
=> Add evidences to IdDocument credential

__test__/claim/Claim.test.js, package-lock.json, package.json, src/claim/Claim.js
Resolve UCAs type when it is a UCA with the `alias` flag on Claim conversion.
=> Handle alias UCAs on Claim transformation

__test__/creds/VerifiableCredential.test.js, package-lock.json, package.json, src/creds/VerifiableCredential.js, src/creds/definitions.js
Evidences claim is no longer required while issuing IdDocument credential.
=> Make evidences optional in idDocument credential

package-lock.json, package.json, src/errors/definitions.js
New error code for phone validation:
- `error.idv.validation.invalid.phone`
New error code for email validation:
- `error.idv.validation.invalid.email`
New error codes for token validation:
- `error.idv.token.sending.failed`
- `error.idv.token.expired`
- `error.idv.token.mismatch`
=> Define new error codes for phone and email validation

__test__/creds/VerifiableCredential.test.js, package-lock.json, package.json, src/creds/VerifiableCredential.js
Expose `requesterGrantVerify` that allows the client to verify if a credential was granted for a specific requester and requestId.
This method can run against a credential object (parsed from a Json), so it does not require a `VerifiableCredential` instance as parameter.
Usage example:
```
const { VC } = require('@identity.com/credential-commons');
const credential = require('credential.json');   // load a credential json
const verifyGrant = VC.requesterGrantVerify(credential, 'requestorId', 'requestId');
```
`requestorId` and `requestId` must be the same values used on `grantUsageFor`.
=> Expose a method to verify the credential grant

__test__/creds/VerifiableCredential.test.js, package-lock.json, package.json, src/creds/VerifiableCredential.js, src/timeHelper.js
The `unix-timestap` has a bug when transforming string deltas to a timestamp. `moment` in the other hand does it right.
So THIS includeS a new timeHelper that uses `moment-mini` to handle that conversion.
=> quickfix to better handle time deltas like `-21y`

__test__/creds/VerifiableCredential.test.js, src/creds/definitions.js
Rename Covid19 credential to be like the others with no 'Medical' component in its title, so it's now: `credential-cvc:Covid19-v1` rather than `credential-cvc:Medical.Covid19-v1`
=> remove `Medical` from Covid19 credential defn

__test__/services/AggregationService.test.js, src/AggregationHandler.js
- fixes the $max and min operator
- handle both 'true' and true as parameters
=> BUG FIX: max/min and boolean params

AUDIT.md, audit-ci.json, package-lock.json, package.json, src/errors/definitions.js
Added ERROR_IDV_CREDENTIAL_FAILED_ANCHORING (`error.idv.credential.failed.anchoring`) to the IDV errors definition.
Fix audit issues.
=> CIV-3145 - Add error code for anchoring failures

__test__/CredentialSignerVerifier.test.js, __test__/creds/VerifiableCredential.test.js, src/creds/CredentialSignerVerifier.js, src/creds/CvcMerkleProof.js, src/creds/VerifiableCredential.js
This is to add a `merkleRootSignature` property in the credential `proof`. With that is possible to verifiy the full integrity of the credential merkletree without the need to an on chain anchor.
An example of a 
```
{
algo: 'ec256k1',
pubBase58: 'xpub661MyMwAqRbcH4Fx3W36ddbLfZwHsguhE6x7JxwbX5E1hY8ov9L4CrNfCCQpV8pVK64CVqkhYQ9QLFgkVAUqkRThkTY1R4GiWHNZtAFSVpD',
signature: '3045022100e7f0921491e8da2759b24047443325483ac023795683dc3b91c78d0566a1159602206fd4e80982fd83705932543d02bc6abd079446bf4ec7b5d9fba4f7f5363bd6fa',
}
```
To get the `proof` signed like that an signer instance(must implement the `sign` function) needs to provided in the constructor. The signer is optional.
This also implements a CredentialSignerVerifier as reference and convenience implementation to sign and verify the …
=> CIV-3154 Merkletree Sign and Verify

__test__/creds/VerifiableCredential.test.js, __test__/schema/fixtures/credential-test:IdDocument-v1.schema.json, package.json, src/schemas/jsonSchema/index.js
Updated to check for referenced schema in a credential schema.
Added a test schema loader to load anything starting with credential-test:* from fixtures to be used in tests
=> IDCOM-1592 Updated to check for properties in references schemas
